### ISSUE TITLE
Tests are failing do to a missing dependency.

### ISSUE THREAD

**Issue by dmtucker** [dmtucker/ogre#13]
```
[2015-05-29T15:06:01-0700] david@animus.cosmarium.net $ python -m unittest discover
EE......
======================================================================
ERROR: ogre.test.test_api (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: ogre.test.test_api
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/david/projects/ogre/ogre/test/test_api.py", line 19, in <module>
    from mock import MagicMock
ImportError: No module named mock


======================================================================
ERROR: ogre.test.test_Twitter (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: ogre.test.test_Twitter
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/david/projects/ogre/ogre/test/test_Twitter.py", line 20, in <module>
    from mock import MagicMock
ImportError: No module named mock


----------------------------------------------------------------------
Ran 8 tests in 0.056s

FAILED (errors=2)
```
Is this expected?

**Comment by dmtucker** [comment]
Yes, this is expected; however, is it appropriate to add `mock` to the dependency list in `setup.py`?

**Comment by dmtucker** [comment]
Yes, but to `tests_require`, though, not to `install_requires`. Also, by specifying `test_suite`, the tests can be ran as `python setup.py test`. See commit cfea72c.
