### ISSUE TITLE
Tests are failing due to missing Twitter keys.

### ISSUE THREAD

**Issue by dmtucker** [dmtucker/ogre#14]
```
[2015-05-29T15:11:13-0700] david@animus.cosmarium.net $ python -m unittest discover
.EEE......
======================================================================
ERROR: test_fetch (ogre.test.test_api.OGReTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/projects/ogre/ogre/test/test_api.py", line 199, in test_fetch
    network=self.network
  File "/Users/david/projects/ogre/ogre/Twitter.py", line 240, in twitter
    interval=interval
  File "/Users/david/projects/ogre/ogre/Twitter.py", line 75, in sanitize_twitter
    raise ValueError("Twitter API keys are required.")
ValueError: Twitter API keys are required.

======================================================================
ERROR: test_sanitize_twitter (ogre.test.test_Twitter.TwitterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/projects/ogre/ogre/test/test_Twitter.py", line 219, in test_sanitize_twitter
    keyword="test"
  File "/Users/david/projects/ogre/ogre/Twitter.py", line 75, in sanitize_twitter
    raise ValueError("Twitter API keys are required.")
ValueError: Twitter API keys are required.

======================================================================
ERROR: test_twitter (ogre.test.test_Twitter.TwitterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/projects/ogre/ogre/test/test_Twitter.py", line 319, in test_twitter
    network=network
  File "/Users/david/projects/ogre/ogre/Twitter.py", line 240, in twitter
    interval=interval
  File "/Users/david/projects/ogre/ogre/Twitter.py", line 75, in sanitize_twitter
    raise ValueError("Twitter API keys are required.")
ValueError: Twitter API keys are required.

----------------------------------------------------------------------
Ran 10 tests in 0.075s

FAILED (errors=3)
```
Is this expected?

**Comment by dmtucker** [comment]
Yes, keys must be specified one way or another.
``` sh
env TWITTER_CONSUMER_KEY=fake TWITTER_ACCESS_TOKEN=fake python setup.py test
```
